name: Check Secrets

on:  
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:                      
  check-secrets:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
      - run: npm install findit
      - run: node find.js google-services.json secrets.xml 


